import {
  Entity, PrimaryGeneratedColumn, Column, Index, OneToMany,
  CreateDateColumn,
} from 'typeorm';
import { QuizBundleQuestion } from './quiz-bundle-question.entity';

/**
 * A CSV bundle generated by Content Studio for upload into the admin Quiz
 * Module. Independent of cs_delivered_quizzes (which is the 9-Q Saturday XLSX).
 * The UI panel's count + toughness drive what gets generated.
 */
@Entity('cs_quiz_bundles')
export class QuizBundle {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Index()
  @Column({ type: 'uuid', name: 'plan_id' })
  planId: string;

  @Column({ type: 'uuid', name: 'brand_id' })
  brandId: string;

  @Column({ type: 'date', name: 'week_of' })
  weekOf: string;

  // LLM-authored metadata — copied straight into the admin Quiz Module's
  // title + description fields when the user creates the quiz there.
  @Column({ type: 'text' })
  title: string;

  @Column({ type: 'text' })
  description: string;

  // Numeric tie-breaker — tolerance 0 ⇒ exact / closest-guess wins.
  @Column({ type: 'text', name: 'tie_breaker_question' })
  tieBreakerQuestion: string;

  @Column({ type: 'numeric', name: 'tie_breaker_answer' })
  tieBreakerAnswer: string;

  @Column({ type: 'numeric', name: 'tie_breaker_tolerance', default: 0 })
  tieBreakerTolerance: string;

  @Column({ type: 'varchar', length: 60, nullable: true, name: 'tie_breaker_unit' })
  tieBreakerUnit: string | null;

  @Column({ type: 'int', name: 'question_count' })
  questionCount: number;

  @Column({ type: 'int' })
  toughness: number;

  /**
   * The number written into every row's `quiz_week` column when this bundle
   * is downloaded as CSV. Picked in the UI before generate; the download
   * endpoint still honours ?quizWeek=N for ad-hoc overrides.
   */
  @Column({ type: 'int', nullable: true, name: 'quiz_week' })
  quizWeek: number | null;

  @Column({ type: 'varchar', length: 80, nullable: true, name: 'generator_model' })
  generatorModel: string | null;

  @Column({ type: 'numeric', precision: 10, scale: 6, name: 'cost_usd', default: 0 })
  costUsd: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @OneToMany(() => QuizBundleQuestion, (q) => q.bundle)
  questions: QuizBundleQuestion[];
}
