-- Quiz promotion social posts — generated by LLM from the bundle's
-- title/description/tie-breaker + the plan's lessons (with their published
-- YouTube URLs) + brand context. The LLM also picks the start/end time and
-- reward amount based on the brand's locale + voice; humans can regenerate
-- if they don't like the values.
--
-- One package per bundle. Each package payload is jsonb so we can evolve
-- the per-platform shape without further migrations.

CREATE TABLE IF NOT EXISTS cs_quiz_promo_packages (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bundle_id         uuid NOT NULL UNIQUE
                      REFERENCES cs_quiz_bundles(id) ON DELETE CASCADE,
  plan_id           uuid NOT NULL
                      REFERENCES cs_weekly_content_plans(id) ON DELETE CASCADE,
  brand_id          uuid NOT NULL,

  -- LLM-picked schedule + reward, stored as plain text so they can render
  -- in any locale/format the model chose (e.g. "Sat 9 PM IST – Sun 9 PM IST").
  starts_at_label   text NOT NULL,
  ends_at_label     text NOT NULL,
  reward_label      text NOT NULL,        -- e.g. "₹500 Amazon gift card"

  -- Per-platform payloads. See QuizPromoAgent for the exact shape — each
  -- carries title/body/hashtags/full_text + a shared social_footer block.
  payload           jsonb NOT NULL DEFAULT '{}'::jsonb,

  generator_model   varchar(80),
  cost_usd          numeric(10,6) NOT NULL DEFAULT 0,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cs_quiz_promo_packages_plan
  ON cs_quiz_promo_packages(plan_id);
